services:
  iiq-app:
    image: iiq-app
    build: 
      context: ./iiq_app
      args:
        - SSB_APP_FOLDER=$ssb_app_folder
        - SPTARGET=$sp_target
        - FULL_TEXT_INDEX_PATH=/mnt/iiq-fulltext-index
        - UPLOAD_FILE_PATH=/mnt/file-upload
    container_name: iiq-app
    ports:
      - 8080:8080
      - 8443:8443
    environment:
      - CATALINA_OPTS=-Xmx1024m -Xms256m
      - TZ=Australia/Sydney
    depends_on:
      - iiq-mssql-db
    volumes:
      - "./volume/sp-log:/usr/local/tomcat/logs"
      - "./volume/keystore/local:/usr/local/keystore"
      - "./volume/iiq-properties/local/mssql/iiq.properties:/usr/local/tomcat/webapps/identityiq/WEB-INF/classes/iiq.properties"
      - "./volume/iiq-properties/local/log4j2.properties:/usr/local/tomcat/webapps/identityiq/WEB-INF/classes/log4j2.properties"

  iiq-mssql-db:
    container_name: iiq-mssql-db
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: always
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: Sailpoint@1234
    ports:
      - 1433:1433
    volumes:
      - ./volume/mssql/data:/var/opt/mssql/data
      - ./volume/mssql/log:/var/opt/mssql/log
      - ./volume/mssql/secrets:/var/opt/mssql/secrets


    